### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by bringrainfire** [Yapeal/yapeal#107]
What's the current situation with yapeal?

**Comment by Dragonrun1** [comment]
Since the XML API is being phased out and being replaced by something different server side I've basically stopped working on it. Also in RL I've become much busier and have less time to do anything with it. If someone is still using it and reports any bugs I would still look to fix them but probably not as quickly as I might have in the past. It has been a few months since I actually even logged in to the game and play it at all as well.
Is there some reason you are really interesting in the project? 

    On Friday, September 29, 2017 10:01 AM, cecil merrell aka bringrainfire <notifications@github.com> wrote:
 

 What's the current situation with yapeal?—

**Comment by bringrainfire** [comment]
Nope was just wondering. I haven't been very active in eve either. Been busy also.
